version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: myrag:latest
    env_file: .env
    container_name: myrag-container
    volumes:
      - ./:/usr/local/app
    # NOTE: tokenを空にするとVSCodeのJupyterのExtensionからkernel指定時にxsrfエラーが出る。raise HTTPError(403, "'_xsrf' argument missing from POST"
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root  --NotebookApp.password=''
    ports:
      - "8888:8888" # localport:dockerport



