version: '3'

services:
  app:
    build:
      context: ./myrag
      dockerfile: Dockerfile
    image: myrag:latest
    env_file: .env
    container_name: myrag-container
    ports:
      - 8000:8000 # localhostport:containerport
    volumes:
      - ./myrag/:/usr/local/app
    command: chainlit run /usr/local/app/myrag/web_ui.py --host=0.0.0.0 --port=8000 -w
